### PR TITLE
Do not crash when opening the main dialog + RuboCop upgrade

### PR DESCRIPTION
**Pull request by imobachgs**
## Problem

The main dialog does not open.

* [bsc#1199552](https://bugzilla.suse.com/show_bug.cgi?id=1199552)

The problem is that an old RuboCop version suggested [this change](https://github.com/yast/yast-iscsi-client/commit/34e4db0e3f9bfdedd552b80b1abe3be7ec4888c1) but `CWM.Run` arguments receives [(widgets, functions, skip_store_for: [])](https://github.com/yast/yast-yast2/blob/master/library/cwm/src/modules/CWM.rb#L773).

## Solution

* Revert the change.
* As a new RuboCop version (1.24, for instance) does not complain, let's upgrade RuboCop instead of disabling that specific Cop. An autogenerated configuration is used.
* Fix SCR `.probe.netcard` call. Otherwise, the package will not build. See [this comment](https://github.com/yast/yast-iscsi-client/pull/118#issuecomment-1123924517) in #118.

## Testing

- *Tested manually*

### CODE REVIEW

**Review by dgdavid — APPROVED** [review]
LGTM. Nice catch, thanks

**Comment by ancorgs** [comment]
As commented here https://github.com/yast/yast-iscsi-client/pull/118#issuecomment-1123924517, I think it's good that now we are mocking the call to `.probe.netcard` so we have more consistent tests.

But the failure in the CI proves that is actually possible to call that agent and get an Array in which one of the entries does not contain the key "drivers". And now that we are removing the failure in the test, we should take the opportunity to make this code more robust: https://github.com/yast/yast-iscsi-client/blob/1b84d3a9ec87da7fc27217b744e94fdd835e37fb/src/modules/IscsiClientLib.rb#L1629

**Comment by ancorgs** [comment]
Regarding my previous comment. Would it be possible to get the output of `.probe.netcard` for the CI system?

**Review by ancorgs — APPROVED** [review]
We agreed to fix the weak `#netcard_modules` as a separate PR. So approving this.

**Review by ancorgs — APPROVED** [review]
Looks even better now, with the underlying problem fixed.

**Pull request merged**
